uploads = []
outputs = []

[[generated]]
id = "-z0TcfBSUaDmpMMrdO_nV"
uri = "file://public/og-default.png"
type = "image"
title = "ramp og default"

[[generated]]
id = "c0ljX8ryRpUTO7YWWnxGb"
uri = "file://public/og-product.png"
type = "image"
title = "ramp og product"

[[generated]]
id = "QL5tvHIjgV6Q8r29FdNfB"
uri = "file://public/og-pricing.png"
type = "image"
title = "ramp og pricing"

[[generated]]
id = "6-5rW4Q16ySrakM7Uo8FG"
uri = "file://public/og-company.png"
type = "image"
title = "ramp og company"

[[generated]]
id = "oCqAh2MbgNA0DHmyvmFtt"
uri = "file://public/og-resources.png"
type = "image"
title = "ramp og resources"

[[generated]]
id = "zY-0C5fwZCDmQbdL6YwSS"
uri = "file://public/og-resources-blog.png"
type = "image"
title = "ramp og blog"

[[generated]]
id = "1qDTR6xU2nyspIiTwHslU"
uri = "file://public/og-resources-customer-stories.png"
type = "image"
title = "ramp og customer stories"

[[generated]]
id = "-Mpafpwe6UH40K3XO0L_J"
uri = "file://public/og-resources-help-center.png"
type = "image"
title = "ramp og help"

[[generated]]
id = "RoNPx1rWAkkdVSdhrJDNR"
uri = "file://public/og-resources-guides.png"
type = "image"
title = "ramp og guides"

[[generated]]
id = "NeX0d6FmzCfchYTzNRhed"
uri = "file://public/og-resources-api-docs.png"
type = "image"
title = "ramp og api"
